### ISSUE TITLE
Authentication issues with Search API in Python3.9 Library

### ISSUE THREAD

**Issue by mark-de-haan** [googleapis/python-retail#126]
Hello,

I have been running into a 403 permission error when trying to use the Retail Search API in python

I have a service account key file set as GOOGLE_APPLICATION_CREDENTIALS
```sh
export GOOGLE_APPLICATION_CREDENTIALS="path_to_key_file"
```

The service account has had Retail Viewer, Retail Admin, and Owner roles to get this to work. None did.

This project has access to the Retail API and I already loaded products into the catalog. Trying out the search function in the console it self works just fine.

Here is my python code
```python
from typing import List

from google.cloud.retail_v2 import SearchServiceClient
from google.cloud.retail_v2.types.search_service import (SearchRequest,
                                                         SearchResponse)

# The identifier of the GCP project
PROJECT_ID: str = "my-project-id"

# The identifier of the serving configuration
SERVING_CONFIG_ID: str = "my-serving-config-id"

# The identifier of the product branch. Retail API allows us to load multiple branches
# 0 is the default. Leaving it empty will always select the default branch
BRANCH_ID: str = "1"

# The identifier of the visitor, as sent to Google Tag Manager
VISITOR_ID: str = None

search_client = SearchServiceClient()

search_request = SearchRequest()
search_request.placement = f"projects/{PROJECT_ID}/locations/global/catalogs/default_catalog/placements/{SERVING_CONFIG_ID}"
search_request.branch = f"projects/{PROJECT_ID}/locations/global/catalogs/default_catalog/branches/{BRANCH_ID}"
search_request.query = "my-query"
search_request.visitor_id = VISITOR_ID

print(search_request)
search_response: SearchResponse = search_client.search()
search_results: List[SearchResponse.SearchResult] = search_response.results

for result in search_results:
    print(result)
```

Library version: google-cloud-retail 1.2.1

Full error message

```sh
Traceback (most recent call last):
  File "/home/mdh/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/mdh/.local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mdh/.local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.PERMISSION_DENIED
        details = "The caller does not have permission"
        debug_error_string = "{"created":"@1640766472.137486780","description":"Error received from peer ipv4:142.251.36.170:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"The caller does not have permission","grpc_status":7}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mdh/git/gists/search_service_example.py", line 29, in <module>
    search_response: SearchResponse = search_client.search()
  File "/home/mdh/.local/lib/python3.9/site-packages/google/cloud/retail_v2/services/search_service/client.py", line 435, in search
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/mdh/.local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py", line 142, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/mdh/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.PermissionDenied: 403 The caller does not have permission
```

**Comment by busunkim96** [comment]
Hi @mark-de-haan,

I see you explicitly set `GOOGLE_APPLICATION_CREDENTIALS` so it seems unlikely, but could you try the following code snippet to confirm the library is using the expected service account and project?

```py
import google.auth

credentials, project_id = google.auth.default()
```

Are you able to make any other calls to the Retail API successfully using the client library?

**Comment by mark-de-haan** [comment]
Hi, Happy New Year!

Yes I was able to list the catalogs using the same service account.

```py
from google.cloud.retail_v2 import CatalogServiceClient
from google.cloud.retail_v2.services.catalog_service.pagers import \
    ListCatalogsPager

catalog_client: CatalogServiceClient = CatalogServiceClient()
catalogs: ListCatalogsPager = catalog_client.list_catalogs()

for catalog in catalogs:
    print(catalog)
```

Verifying with the snippet you provided confirmed that the set service account is being used.

**Comment by busunkim96** [comment]
Awesome, thank you for checking.

I looked through the cloud.google.com docs for this API and it looks like the feature needs to be enabled per-project:

> This feature is only available for users who have Retail Search enabled. Please submit a form [here](https://cloud.google.com/contact) to contact cloud sales if you are interested in using Retail Search.

https://cloud.google.com/retail/docs/reference/rpc/google.cloud.retail.v2#google.cloud.retail.v2.SearchService

Have you gone through this process already?

**Comment by mark-de-haan** [comment]
Hi,

Yes I went through the process and everything is enabled. I had contact with the retail support team and managed to fix it.

Three things
- You should not use **project ID** but **project number**
- Visitor ID can not be None
- I had a typo where I forgot to include the search_request variable inside the search() call

See updated python code below

```python
from typing import List

from google.cloud.retail_v2 import SearchServiceClient
from google.cloud.retail_v2.types.search_service import (SearchRequest,
                                                         SearchResponse)

# The number of the GCP project
PROJECT_NUMBER: str = "my-project-number"

# The identifier of the serving configuration
SERVING_CONFIG_ID: str = "my-serving-config-id"

# The identifier of the product branch. Retail API allows us to load multiple branches
# 0 is the default. Leaving it empty will always select the default branch
BRANCH_ID: str = "1"

# The identifier of the visitor, as sent to Google Tag Manager
VISITOR_ID: str = "test"

search_client = SearchServiceClient()

search_request = SearchRequest()
search_request.placement = f"projects/{PROJECT_NUMBER}/locations/global/catalogs/default_catalog/placements/{SERVING_CONFIG_ID}"
search_request.branch = f"projects/{PROJECT_NUMBER}/locations/global/catalogs/default_catalog/branches/{BRANCH_ID}"
search_request.query = "my-query"
search_request.visitor_id = VISITOR_ID

print(search_request)
search_response: SearchResponse = search_client.search(search_request)
search_results: List[SearchResponse.SearchResult] = search_response.results

for result in search_results:
    print(result)
```

So this issue can be closed as resolved.
Thanks for the help!
